image: maven:3-jdk-12

build:
  script: mvn clean package sonar:sonar -Dsonar.projectKey=AirbornePanda_VaadinSpringBootStarter -Dsonar.organization=airbornepanda -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN